### ISSUE TITLE
Incorrect pin outs for logic chips like SN74LS02N

### ISSUE THREAD

**Issue by StevenChristy** [digikey/digikey-kicad-library#10]
The digikey library has incorrect pinouts for logic chips. As an example, if you compare the pinouts of SN74LS02N in KiCad with the datasheet, you'll see that in KiCad it shows 1A = 1, 1B = 2, 1Y = 3. The correct pinout shown on the datasheet is 1Y = 1, 1A = 2, 1B = 3. The mistake isn't limited to this one logic chip either. Its repeated elsewhere in the library.

**Comment by bombledmonk** [comment]
I'll take a look.

**Comment by bombledmonk** [comment]
I believe this was corrected by pull request #11 .  Thanks for reporting.  If you see any other problems please let us know.
