### ISSUE TITLE
BAT-54 symbol issue

### ISSUE THREAD

**Issue by ejthesnaar** [digikey/digikey-kicad-library#17]
Both dk_Diodes-Rectifiers-Arrays:BAT54C and dk_Diodes-Rectifiers-Arrays:BAT54C-7-F have incorrect symbols for digikey-footprints:SOT-23-3.

The common cathode should be on pin 3, not pin 1.
The anode of the first diode should be on pin 1, not pin 3.

The following unified diff should fix both symbols:

```
-X ~ 1 400 -100 200 L 50 50 1 1 I
+X ~ 1 -200 0 200 R 50 50 1 1 I
 X ~ 2 -200 -200 200 R 50 50 1 1 I
-X ~ 3 -200 0 200 R 50 50 1 1 I
+X ~ 3 400 -100 200 L 50 50 1 1 I
```

**Comment by bombledmonk** [comment]
This did get fixed a while ago, just closing out issues.
