### ISSUE TITLE
Lack of searchable / 'type ahead' content for the Alpha library

### ISSUE THREAD

**Issue by BGwiz** [digikey/digikey-kicad-library#3]
Plenty of searchable material to help locate using the 'type ahead' method... 
![image](https://user-images.githubusercontent.com/30243200/32957795-4e939ae2-cb82-11e7-8cbf-5113d1cec5cb.png)

Lack of said material in the Alpha version...
![image](https://user-images.githubusercontent.com/30243200/32957901-8ee38242-cb82-11e7-81cc-f7bc1f142591.png)

![image](https://user-images.githubusercontent.com/30243200/32959417-354f5184-cb87-11e7-9851-c2768854e43b.png)

**Comment by bombledmonk** [comment]
Looks like the .dcm file isn't correctly being reassembled.  I'll take a look.

**Comment by bombledmonk** [comment]
@BGwiz Want to check this one also?
