### ISSUE TITLE
401-2002-1-ND fooprint pin numbers direction at top is wrong

### ISSUE THREAD

**Issue by kasbah** [digikey/digikey-kicad-library#5]
In the [datasheet](https://www.ckswitches.com/media/1422/js.pdf) and your symbol for JS202011SCQN the pins at the top go 4 5 6 but in the footprint it goes 6 5 4.

**Comment by bombledmonk** [comment]
@kasbah I pushed some changes to this, would you mind checking it out?

**Comment by kasbah** [comment]
Looks good to me! 

Can I ask you why you name this footprint the Digikey SKU rather than the MPN (JS202011SCQN)? Seems like the SKU will always just point at the part with that MPN.

**Comment by bombledmonk** [comment]
The footprints still need to go through naming cleanup.  The next update will be more in tune with the KCL and MFG PNs where appropriate.
