### ISSUE TITLE
Fix footprint for the PEC11R-4215F-S0024 rotary encoder

### ISSUE THREAD

**Issue by aklofas** [digikey/digikey-kicad-library#50]
According to the kicad footprint, common/ground is third (right) pin. According the datasheet, common/ground is the 2nd (middle) pin.

**Comment by aklofas** [comment]
--- a/digikey-footprints.pretty/Rotary_Encoder_Switched_PEC11R.kicad_mod	2018-05-06 15:47:24.136629584 -0700
+++ b/digikey-footprints.pretty/Rotary_Encoder_Switched_PEC11R.kicad_mod	2018-06-07 22:36:31.556059433 -0700
@@ -29,6 +29,6 @@
   (pad 1 thru_hole circle (at 3.2 -7) (size 2 2) (drill 1) (layers *.Cu *.Mask))
   (pad 2 thru_hole circle (at 8.2 -7) (size 2 2) (drill 1) (layers *.Cu *.Mask))
   (pad A thru_hole circle (at 3.2 7.5) (size 2 2) (drill 1) (layers *.Cu *.Mask))
-  (pad B thru_hole circle (at 5.7 7.5) (size 2 2) (drill 1) (layers *.Cu *.Mask))
-  (pad C thru_hole circle (at 8.2 7.5) (size 2 2) (drill 1) (layers *.Cu *.Mask))
+  (pad B thru_hole circle (at 8.2 7.5) (size 2 2) (drill 1) (layers *.Cu *.Mask))
+  (pad C thru_hole circle (at 5.7 7.5) (size 2 2) (drill 1) (layers *.Cu *.Mask))
 )

**Comment by bombledmonk** [comment]
This should be fixed in the latest commit.  3169728
