### ISSUE TITLE
TO-92 package backwards?

### ISSUE THREAD

**Issue by ShawnHymel** [digikey/digikey-kicad-library#66]
I realize that many transistors label EBC in any arbitrary order, but a popular BJT on digikey's site ([2N3904BU](https://www.digikey.com/products/en?keywords=2N3904BU)) seems to have it's silkscreen reversed on the TO-92 package (assuming pins 1, 2, 3 line up with E, B, C).

**Comment by Reid-L** [comment]
@ShawnHymel 
Hi Shawn,

Thanks for the feedback. Are you using the most current version of the library? We did correct several errors in the transistor portion of the library on the last few updates. Here is the current version:
![image](https://user-images.githubusercontent.com/33766926/42042071-e7f6ccc8-7ab8-11e8-92b2-b3964e3822c1.png)
![image](https://user-images.githubusercontent.com/33766926/42042955-e29cc7f8-7aba-11e8-9718-38b9505c5194.png)
![image](https://user-images.githubusercontent.com/33766926/42042098-fa42ed94-7ab8-11e8-8de4-0cd2711cc420.png)
I hope this helps

**Comment by ShawnHymel** [comment]
I did not...I was using the version from a few months ago. Thanks for letting me know!
