### ISSUE TITLE
Schematic Symbol for Battery Holders?

### ISSUE THREAD

**Issue by ShawnHymel** [digikey/digikey-kicad-library#83]
I'm trying to add a Keystone 3034 (https://www.digikey.com/product-detail/en/keystone-electronics/3034TR/36-3034CT-ND/4833649) to my project. I noticed that its footprint is already in the digikey-kicad-library. However, there does not seem to be an associated schematic symbol for it. Is there a particular symbol I should be using?

**Comment by Reid-L** [comment]
@ShawnHymel 
Can you specify which footprint it is that you are looking at and I will see what I can do?

**Comment by ShawnHymel** [comment]
Nevermind....it's a footprint that comes with KiCad. Still learning my way around 5.0. Sorry!
