### ISSUE TITLE
dk_Embedded-Microcontrollers:ATMEGA2560-16AU missing VCC and GND

### ISSUE THREAD

**Issue by theshadow124** [digikey/digikey-kicad-library#89]
Hello,

I was trying to use the symbol dk_Embedded-Microcontrollers:ATMEGA2560-16AU and it has no VCC or GND pins? everything else looks correct though.

I have never made my own footprints for KiCad, but I will try to fix it and upload it.

Thanks,
Kyle

**Comment by jacky4566** [comment]
You need to place both A and B parts of the symbol. All the VCC/GND pins are on Part B.

**Comment by theshadow124** [comment]
O, ok great!

I am nearly done rebuilding the footprint to group everything by port instead of sequential pin numbers, would this be something I should post?
